(define (domain blocks-domain)
    (:requirements :conditional-effects :derived-predicates :disjunctive-preconditions :negative-preconditions :strips :typing)
    (:types block)
    (:predicates (Y-Oholding_b1-and-not-YOnot-ontable_b1) (Y-Onot-ontable_b1) (Y-Oon_b2_b3-and-not-YOnot-ontable_b1) (Y-Oon_b3_b4-and-not-YOnot-ontable_b1) (Y-Oon_b4_b5-and-not-YOnot-ontable_b1) (YOnot-ontable_b1) (clear ?x - block)  (emptyhand) (holding ?x - block)  (on ?x - block ?y - block)  (ontable ?x - block)  (val-Oholding_b1-and-not-YOnot-ontable_b1) (val-Onot-ontable_b1) (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (val-Oon_b2_b3-and-not-YOnot-ontable_b1-and-Oon_b3_b4-and-not-YOnot-ontable_b1-and-Oon_b4_b5-and-not-YOnot-ontable_b1-and-Oholding_b1-and-not-YOnot-ontable_b1) (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (val-YOnot-ontable_b1) (val-holding_b1) (val-holding_b1-and-not-YOnot-ontable_b1) (val-not-YOnot-ontable_b1) (val-not-ontable_b1) (val-on_b2_b3) (val-on_b2_b3-and-not-YOnot-ontable_b1) (val-on_b3_b4) (val-on_b3_b4-and-not-YOnot-ontable_b1) (val-on_b4_b5) (val-on_b4_b5-and-not-YOnot-ontable_b1) (val-ontable_b1))
    (:derived (val-Oholding_b1-and-not-YOnot-ontable_b1) (or (val-holding_b1-and-not-YOnot-ontable_b1) (Y-Oholding_b1-and-not-YOnot-ontable_b1)))
     (:derived (val-Onot-ontable_b1) (or (val-not-ontable_b1) (Y-Onot-ontable_b1)))
     (:derived (val-Onot-ontable_b1) (or (val-not-ontable_b1) (Y-Onot-ontable_b1)))
     (:derived (val-Onot-ontable_b1) (or (val-not-ontable_b1) (Y-Onot-ontable_b1)))
     (:derived (val-Onot-ontable_b1) (or (val-not-ontable_b1) (Y-Onot-ontable_b1)))
     (:derived (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (or (val-on_b2_b3-and-not-YOnot-ontable_b1) (Y-Oon_b2_b3-and-not-YOnot-ontable_b1)))
     (:derived (val-Oon_b2_b3-and-not-YOnot-ontable_b1-and-Oon_b3_b4-and-not-YOnot-ontable_b1-and-Oon_b4_b5-and-not-YOnot-ontable_b1-and-Oholding_b1-and-not-YOnot-ontable_b1) (and (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (val-Oholding_b1-and-not-YOnot-ontable_b1)))
     (:derived (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (or (val-on_b3_b4-and-not-YOnot-ontable_b1) (Y-Oon_b3_b4-and-not-YOnot-ontable_b1)))
     (:derived (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (or (val-on_b4_b5-and-not-YOnot-ontable_b1) (Y-Oon_b4_b5-and-not-YOnot-ontable_b1)))
     (:derived (val-YOnot-ontable_b1) (YOnot-ontable_b1))
     (:derived (val-YOnot-ontable_b1) (YOnot-ontable_b1))
     (:derived (val-YOnot-ontable_b1) (YOnot-ontable_b1))
     (:derived (val-YOnot-ontable_b1) (YOnot-ontable_b1))
     (:derived (val-holding_b1) (holding b1))
     (:derived (val-holding_b1-and-not-YOnot-ontable_b1) (and (val-holding_b1) (val-not-YOnot-ontable_b1)))
     (:derived (val-not-YOnot-ontable_b1) (not (val-YOnot-ontable_b1)))
     (:derived (val-not-YOnot-ontable_b1) (not (val-YOnot-ontable_b1)))
     (:derived (val-not-YOnot-ontable_b1) (not (val-YOnot-ontable_b1)))
     (:derived (val-not-YOnot-ontable_b1) (not (val-YOnot-ontable_b1)))
     (:derived (val-not-ontable_b1) (not (val-ontable_b1)))
     (:derived (val-not-ontable_b1) (not (val-ontable_b1)))
     (:derived (val-not-ontable_b1) (not (val-ontable_b1)))
     (:derived (val-not-ontable_b1) (not (val-ontable_b1)))
     (:derived (val-on_b2_b3) (on b2 b3))
     (:derived (val-on_b2_b3-and-not-YOnot-ontable_b1) (and (val-on_b2_b3) (val-not-YOnot-ontable_b1)))
     (:derived (val-on_b3_b4) (on b3 b4))
     (:derived (val-on_b3_b4-and-not-YOnot-ontable_b1) (and (val-on_b3_b4) (val-not-YOnot-ontable_b1)))
     (:derived (val-on_b4_b5) (on b4 b5))
     (:derived (val-on_b4_b5-and-not-YOnot-ontable_b1) (and (val-on_b4_b5) (val-not-YOnot-ontable_b1)))
     (:derived (val-ontable_b1) (ontable b1))
     (:derived (val-ontable_b1) (ontable b1))
     (:derived (val-ontable_b1) (ontable b1))
     (:derived (val-ontable_b1) (ontable b1))
    (:action pick-up
        :parameters (?x - block)
        :precondition (and (clear ?x) (ontable ?x) (emptyhand))
        :effect (and (not (ontable ?x)) (not (clear ?x)) (not (emptyhand)) (holding ?x) (when (not (val-Onot-ontable_b1)) (not (Y-Onot-ontable_b1))) (when (not (val-Oon_b4_b5-and-not-YOnot-ontable_b1)) (not (Y-Oon_b4_b5-and-not-YOnot-ontable_b1))) (when (not (val-Oon_b2_b3-and-not-YOnot-ontable_b1)) (not (Y-Oon_b2_b3-and-not-YOnot-ontable_b1))) (when (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (Y-Oon_b2_b3-and-not-YOnot-ontable_b1)) (when (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (Y-Oon_b3_b4-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (YOnot-ontable_b1)) (when (not (val-Oon_b3_b4-and-not-YOnot-ontable_b1)) (not (Y-Oon_b3_b4-and-not-YOnot-ontable_b1))) (when (val-Oholding_b1-and-not-YOnot-ontable_b1) (Y-Oholding_b1-and-not-YOnot-ontable_b1)) (when (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (Y-Oon_b4_b5-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (Y-Onot-ontable_b1)) (when (not (val-Onot-ontable_b1)) (not (YOnot-ontable_b1))) (when (not (val-Oholding_b1-and-not-YOnot-ontable_b1)) (not (Y-Oholding_b1-and-not-YOnot-ontable_b1))))
    )
     (:action put-down
        :parameters (?x - block)
        :precondition (holding ?x)
        :effect (and (not (holding ?x)) (clear ?x) (emptyhand) (ontable ?x) (when (not (val-Onot-ontable_b1)) (not (Y-Onot-ontable_b1))) (when (not (val-Oon_b4_b5-and-not-YOnot-ontable_b1)) (not (Y-Oon_b4_b5-and-not-YOnot-ontable_b1))) (when (not (val-Oon_b2_b3-and-not-YOnot-ontable_b1)) (not (Y-Oon_b2_b3-and-not-YOnot-ontable_b1))) (when (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (Y-Oon_b2_b3-and-not-YOnot-ontable_b1)) (when (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (Y-Oon_b3_b4-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (YOnot-ontable_b1)) (when (not (val-Oon_b3_b4-and-not-YOnot-ontable_b1)) (not (Y-Oon_b3_b4-and-not-YOnot-ontable_b1))) (when (val-Oholding_b1-and-not-YOnot-ontable_b1) (Y-Oholding_b1-and-not-YOnot-ontable_b1)) (when (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (Y-Oon_b4_b5-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (Y-Onot-ontable_b1)) (when (not (val-Onot-ontable_b1)) (not (YOnot-ontable_b1))) (when (not (val-Oholding_b1-and-not-YOnot-ontable_b1)) (not (Y-Oholding_b1-and-not-YOnot-ontable_b1))))
    )
     (:action stack
        :parameters (?x - block ?y - block)
        :precondition (and (holding ?x) (clear ?y))
        :effect (and (not (holding ?x)) (not (clear ?y)) (clear ?x) (emptyhand) (on ?x ?y) (when (not (val-Onot-ontable_b1)) (not (Y-Onot-ontable_b1))) (when (not (val-Oon_b4_b5-and-not-YOnot-ontable_b1)) (not (Y-Oon_b4_b5-and-not-YOnot-ontable_b1))) (when (not (val-Oon_b2_b3-and-not-YOnot-ontable_b1)) (not (Y-Oon_b2_b3-and-not-YOnot-ontable_b1))) (when (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (Y-Oon_b2_b3-and-not-YOnot-ontable_b1)) (when (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (Y-Oon_b3_b4-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (YOnot-ontable_b1)) (when (not (val-Oon_b3_b4-and-not-YOnot-ontable_b1)) (not (Y-Oon_b3_b4-and-not-YOnot-ontable_b1))) (when (val-Oholding_b1-and-not-YOnot-ontable_b1) (Y-Oholding_b1-and-not-YOnot-ontable_b1)) (when (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (Y-Oon_b4_b5-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (Y-Onot-ontable_b1)) (when (not (val-Onot-ontable_b1)) (not (YOnot-ontable_b1))) (when (not (val-Oholding_b1-and-not-YOnot-ontable_b1)) (not (Y-Oholding_b1-and-not-YOnot-ontable_b1))))
    )
     (:action unstack
        :parameters (?x - block ?y - block)
        :precondition (and (on ?x ?y) (clear ?x) (emptyhand))
        :effect (and (holding ?x) (clear ?y) (not (clear ?x)) (not (emptyhand)) (not (on ?x ?y)) (when (not (val-Onot-ontable_b1)) (not (Y-Onot-ontable_b1))) (when (not (val-Oon_b4_b5-and-not-YOnot-ontable_b1)) (not (Y-Oon_b4_b5-and-not-YOnot-ontable_b1))) (when (not (val-Oon_b2_b3-and-not-YOnot-ontable_b1)) (not (Y-Oon_b2_b3-and-not-YOnot-ontable_b1))) (when (val-Oon_b2_b3-and-not-YOnot-ontable_b1) (Y-Oon_b2_b3-and-not-YOnot-ontable_b1)) (when (val-Oon_b3_b4-and-not-YOnot-ontable_b1) (Y-Oon_b3_b4-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (YOnot-ontable_b1)) (when (not (val-Oon_b3_b4-and-not-YOnot-ontable_b1)) (not (Y-Oon_b3_b4-and-not-YOnot-ontable_b1))) (when (val-Oholding_b1-and-not-YOnot-ontable_b1) (Y-Oholding_b1-and-not-YOnot-ontable_b1)) (when (val-Oon_b4_b5-and-not-YOnot-ontable_b1) (Y-Oon_b4_b5-and-not-YOnot-ontable_b1)) (when (val-Onot-ontable_b1) (Y-Onot-ontable_b1)) (when (not (val-Onot-ontable_b1)) (not (YOnot-ontable_b1))) (when (not (val-Oholding_b1-and-not-YOnot-ontable_b1)) (not (Y-Oholding_b1-and-not-YOnot-ontable_b1))))
    )
)