(define (problem grounded-STRIPS-OS-SEQUENCEDSTRIPS-SMALL-4)
    (:domain grounded-STRIPS-OPENSTACKS-SEQUENCEDSTRIPS)
    (:objects )
    (:init (MACHINE-AVAILABLE-) (NOT-MADE-P1) (NOT-MADE-P2) (NOT-MADE-P3) (NOT-MADE-P4) (NOT-MADE-P5) (STACKS-AVAIL-N0) (WAITING-O1) (WAITING-O2) (WAITING-O3) (WAITING-O4) (WAITING-O5))
    (:goal (val-stacks-avail-n2-S-Oshipped-o1-and-Oshipped-o2-and-Oshipped-o3))
)