(define (domain blocks-domain)
    (:requirements :conditional-effects :derived-predicates :disjunctive-preconditions :negative-preconditions :strips :typing)
    (:types block)
    (:predicates (Y-Oholding_b5) (Y-Oon_b1_b2) (Y-Oon_b2_b3) (Y-Oon_b3_b4) (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (clear ?x - block)  (emptyhand) (holding ?x - block)  (on ?x - block ?y - block)  (ontable ?x - block)  (val-Oholding_b5) (val-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (val-Oon_b1_b2) (val-Oon_b2_b3) (val-Oon_b3_b4) (val-holding_b5) (val-on_b1_b2) (val-on_b2_b3) (val-on_b3_b4) (val-ontable_b5) (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4))
    (:derived (val-Oholding_b5) (or (val-holding_b5) (Y-Oholding_b5)))
     (:derived (val-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (and (val-Oholding_b5) (val-Oon_b1_b2) (val-Oon_b2_b3) (val-Oon_b3_b4)))
     (:derived (val-Oon_b1_b2) (or (val-on_b1_b2) (Y-Oon_b1_b2)))
     (:derived (val-Oon_b2_b3) (or (val-on_b2_b3) (Y-Oon_b2_b3)))
     (:derived (val-Oon_b3_b4) (or (val-on_b3_b4) (Y-Oon_b3_b4)))
     (:derived (val-holding_b5) (holding b5))
     (:derived (val-on_b1_b2) (on b1 b2))
     (:derived (val-on_b2_b3) (on b2 b3))
     (:derived (val-on_b3_b4) (on b3 b4))
     (:derived (val-ontable_b5) (ontable b5))
     (:derived (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (or (val-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (and (val-ontable_b5) (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4))))
    (:action pick-up
        :parameters (?x - block)
        :precondition (and (clear ?x) (ontable ?x) (emptyhand))
        :effect (and (not (ontable ?x)) (not (clear ?x)) (not (emptyhand)) (holding ?x) (when (not (val-Oholding_b5)) (not (Y-Oholding_b5))) (when (val-Oholding_b5) (Y-Oholding_b5)) (when (not (val-Oon_b1_b2)) (not (Y-Oon_b1_b2))) (when (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (when (val-Oon_b3_b4) (Y-Oon_b3_b4)) (when (not (val-Oon_b3_b4)) (not (Y-Oon_b3_b4))) (when (val-Oon_b2_b3) (Y-Oon_b2_b3)) (when (val-Oon_b1_b2) (Y-Oon_b1_b2)) (when (not (val-Oon_b2_b3)) (not (Y-Oon_b2_b3))) (when (not (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (not (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4))))
    )
     (:action put-down
        :parameters (?x - block)
        :precondition (holding ?x)
        :effect (and (not (holding ?x)) (clear ?x) (emptyhand) (ontable ?x) (when (not (val-Oholding_b5)) (not (Y-Oholding_b5))) (when (val-Oholding_b5) (Y-Oholding_b5)) (when (not (val-Oon_b1_b2)) (not (Y-Oon_b1_b2))) (when (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (when (val-Oon_b3_b4) (Y-Oon_b3_b4)) (when (not (val-Oon_b3_b4)) (not (Y-Oon_b3_b4))) (when (val-Oon_b2_b3) (Y-Oon_b2_b3)) (when (val-Oon_b1_b2) (Y-Oon_b1_b2)) (when (not (val-Oon_b2_b3)) (not (Y-Oon_b2_b3))) (when (not (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (not (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4))))
    )
     (:action stack
        :parameters (?x - block ?y - block)
        :precondition (and (holding ?x) (clear ?y))
        :effect (and (not (holding ?x)) (not (clear ?y)) (clear ?x) (emptyhand) (on ?x ?y) (when (not (val-Oholding_b5)) (not (Y-Oholding_b5))) (when (val-Oholding_b5) (Y-Oholding_b5)) (when (not (val-Oon_b1_b2)) (not (Y-Oon_b1_b2))) (when (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (when (val-Oon_b3_b4) (Y-Oon_b3_b4)) (when (not (val-Oon_b3_b4)) (not (Y-Oon_b3_b4))) (when (val-Oon_b2_b3) (Y-Oon_b2_b3)) (when (val-Oon_b1_b2) (Y-Oon_b1_b2)) (when (not (val-Oon_b2_b3)) (not (Y-Oon_b2_b3))) (when (not (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (not (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4))))
    )
     (:action unstack
        :parameters (?x - block ?y - block)
        :precondition (and (on ?x ?y) (clear ?x) (emptyhand))
        :effect (and (holding ?x) (clear ?y) (not (clear ?x)) (not (emptyhand)) (not (on ?x ?y)) (when (not (val-Oholding_b5)) (not (Y-Oholding_b5))) (when (val-Oholding_b5) (Y-Oholding_b5)) (when (not (val-Oon_b1_b2)) (not (Y-Oon_b1_b2))) (when (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4) (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (when (val-Oon_b3_b4) (Y-Oon_b3_b4)) (when (not (val-Oon_b3_b4)) (not (Y-Oon_b3_b4))) (when (val-Oon_b2_b3) (Y-Oon_b2_b3)) (when (val-Oon_b1_b2) (Y-Oon_b1_b2)) (when (not (val-Oon_b2_b3)) (not (Y-Oon_b2_b3))) (when (not (val-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4)) (not (Y-ontable_b5-S-Oholding_b5-and-Oon_b1_b2-and-Oon_b2_b3-and-Oon_b3_b4))))
    )
)